apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: postgresql-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: postgresql
    database.port: 5432
    database.user: postgresql
    database.password: postgresql
    database.server.name: dbserver1
    database.dbname: sampledb
    plugin.name: pgoutput